name: mugicpod-on-github-actions
on: workflow_dispatch
jobs:
  execute-magicpod-test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L -O https://github.com/Magic-Pod/magicpod-api-client/releases/download/0.95.0.1/linux64_magicpod-api-client.zip
        curl unzip -q linux64_magicpod-api-client.zip
        SECRET_API_TOKEN="b3fe292fa6d12d413179a96a50207bb64039ec36"
        ./magicpod-api-client batch-run -t ${SECRET_API_TOKEN} -o TRIDENTtest -p Browserdemo -S 1
